export const $id = (id) => document.getElementById(id)

export const boton = $id('agregados__boton')
export const contenedor = $id('container')
export const tarea = $id('agregados__tarea')
export const agregado = $id('agregado')
// export const tareasActual = $id('tareas__actual')
// export const tareasPendientes = $id('tareas__pendiente')
// export const tareasHechas = $id('tareas__hechas')
export const contenedorTareas = $id('contenedor__tareas')
// export const cambiarTema = $id('cambiar__tema')
export const header = $id('header')
