var d = document.getElementById("dibujito");
var lineas = d.getContext("2d");
lineas.beginPath();
lineas.strokeStyle = "red";
lineas.moveTo(20,20);
lineas.lineTo(40,40);
lineas.stroke();
lineas.closePath();
lineas.beginPath();
lineas.strokeStyle = "red";
lineas.moveTo(40,40);
lineas.lineTo(60,20);
lineas.stroke();
lineas.closePath();
lineas.beginPath();
lineas.strokeStyle = "red";
lineas.moveTo(20,20);
lineas.lineTo(60,20);
lineas.stroke();
lineas.closePath();
lineas.beginPath();
lineas.strokeStyle = "red";
lineas.moveTo(100,20);
lineas.lineTo(120,40);
lineas.stroke();
lineas.closePath();
lineas.beginPath();
lineas.strokeStyle = "red";
lineas.moveTo(120,40);
lineas.lineTo(140,20);
lineas.stroke();
lineas.closePath();
lineas.beginPath();
lineas.strokeStyle = "red";
lineas.moveTo(140,20);
lineas.lineTo(100,20);
lineas.stroke();
lineas.closePath();
lineas.beginPath();
lineas.strokeStyle = "red";
lineas.moveTo(55,100);
lineas.lineTo(115,100);
lineas.stroke();
lineas.closePath();
lineas.beginPath();
lineas.strokeStyle = "red";
lineas.moveTo(55,100);
lineas.lineTo(75,70);
lineas.stroke();
lineas.closePath();
lineas.beginPath();
lineas.strokeStyle = "red";
lineas.moveTo(115,100);
lineas.lineTo(95,70);
lineas.stroke();
lineas.closePath();
lineas.beginPath();
lineas.strokeStyle = "red";
lineas.moveTo(95,70);
lineas.lineTo(75,70);
lineas.stroke();
lineas.closePath();
